language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t imri294/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true imri294/docker-react npm run test