language: generic

sudo: required
services:
  - dockerasd

before_install:
  - docker build -t imri294/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true imri29/docker-react npm run test